<?php

/**
 * 1.x snake_case sınıf adları => 2.x PascalCase adları.
 * legacy_autoload.php tarafından kullanılır; 3.0'da kaldırılacak.
 *
 * @return array<string, class-string>
 */

return [
    'nsql\\database\\base_migration' => \nsql\database\BaseMigration::class,
    'nsql\\database\\cache\\adapter_simple_cache' => \nsql\database\cache\AdapterSimpleCache::class,
    'nsql\\database\\cache\\cache_adapter_interface' => \nsql\database\cache\CacheAdapterInterface::class,
    'nsql\\database\\cache\\cache_manager' => \nsql\database\cache\CacheManager::class,
    'nsql\\database\\cache\\in_memory_adapter' => \nsql\database\cache\InMemoryAdapter::class,
    'nsql\\database\\cache\\memcached_adapter' => \nsql\database\cache\MemcachedAdapter::class,
    'nsql\\database\\cache\\query_cache_store' => \nsql\database\cache\QueryCacheStore::class,
    'nsql\\database\\cache\\query_cache_store_factory' => \nsql\database\cache\QueryCacheStoreFactory::class,
    'nsql\\database\\cache\\redis_adapter' => \nsql\database\cache\RedisAdapter::class,
    'nsql\\database\\cache\\safe_serializer' => \nsql\database\cache\SafeSerializer::class,
    'nsql\\database\\config' => \nsql\database\Config::class,
    'nsql\\database\\connection_manager' => \nsql\database\ConnectionManager::class,
    'nsql\\database\\connection_pool' => \nsql\database\ConnectionPool::class,
    'nsql\\database\\drivers\\driver_factory' => \nsql\database\drivers\DriverFactory::class,
    'nsql\\database\\drivers\\driver_interface' => \nsql\database\drivers\DriverInterface::class,
    'nsql\\database\\drivers\\mysql_driver' => \nsql\database\drivers\MysqlDriver::class,
    'nsql\\database\\drivers\\pgsql_driver' => \nsql\database\drivers\PgsqlDriver::class,
    'nsql\\database\\drivers\\sqlite_driver' => \nsql\database\drivers\SqliteDriver::class,
    'nsql\\database\\events\\query_event' => \nsql\database\events\QueryEvent::class,
    'nsql\\database\\exceptions\\error_codes' => \nsql\database\exceptions\ErrorCodes::class,
    'nsql\\database\\logging\\logger' => \nsql\database\logging\Logger::class,
    'nsql\\database\\migration' => \nsql\database\Migration::class,
    'nsql\\database\\migration_manager' => \nsql\database\MigrationManager::class,
    'nsql\\database\\monitoring\\endpoint_guard' => \nsql\database\monitoring\EndpointGuard::class,
    'nsql\\database\\monitoring\\health_check' => \nsql\database\monitoring\HealthCheck::class,
    'nsql\\database\\monitoring\\metrics' => \nsql\database\monitoring\Metrics::class,
    'nsql\\database\\nsql' => \nsql\database\Nsql::class,
    'nsql\\database\\optimization\\memory_monitor' => \nsql\database\optimization\MemoryMonitor::class,
    'nsql\\database\\optimization\\query_optimizer' => \nsql\database\optimization\QueryOptimizer::class,
    'nsql\\database\\orm\\inflector' => \nsql\database\orm\Inflector::class,
    'nsql\\database\\orm\\model' => \nsql\database\orm\Model::class,
    'nsql\\database\\query_builder' => \nsql\database\QueryBuilder::class,
    'nsql\\database\\raw_expression' => \nsql\database\RawExpression::class,
    'nsql\\database\\security\\query_analyzer' => \nsql\database\security\QueryAnalyzer::class,
    'nsql\\database\\security\\sensitive_data_filter' => \nsql\database\security\SensitiveDataFilter::class,
    'nsql\\database\\seeds\\user_seeder' => \nsql\database\seeds\UserSeeder::class,
    'nsql\\database\\traits\\cache_trait' => \nsql\database\traits\CacheTrait::class,
    'nsql\\database\\traits\\connection_trait' => \nsql\database\traits\ConnectionTrait::class,
    'nsql\\database\\traits\\debug_trait' => \nsql\database\traits\DebugTrait::class,
    'nsql\\database\\traits\\error_handling_trait' => \nsql\database\traits\ErrorHandlingTrait::class,
    'nsql\\database\\traits\\error_model_trait' => \nsql\database\traits\ErrorModelTrait::class,
    'nsql\\database\\traits\\log_path_trait' => \nsql\database\traits\LogPathTrait::class,
    'nsql\\database\\traits\\query_analyzer_trait' => \nsql\database\traits\QueryAnalyzerTrait::class,
    'nsql\\database\\traits\\query_events_trait' => \nsql\database\traits\QueryEventsTrait::class,
    'nsql\\database\\traits\\query_execution_trait' => \nsql\database\traits\QueryExecutionTrait::class,
    'nsql\\database\\traits\\query_parameter_trait' => \nsql\database\traits\QueryParameterTrait::class,
    'nsql\\database\\traits\\read_write_split_trait' => \nsql\database\traits\ReadWriteSplitTrait::class,
    'nsql\\database\\traits\\session_facade_trait' => \nsql\database\traits\SessionFacadeTrait::class,
    'nsql\\database\\traits\\statement_cache_trait' => \nsql\database\traits\StatementCacheTrait::class,
    'nsql\\database\\traits\\streaming_trait' => \nsql\database\traits\StreamingTrait::class,
    'nsql\\database\\traits\\transaction_trait' => \nsql\database\traits\TransactionTrait::class,
    'nsql\\database\\traits\\write_operations_trait' => \nsql\database\traits\WriteOperationsTrait::class,
    'nsql\\database\\validation\\validator' => \nsql\database\validation\Validator::class,
    'nsql\\security\\audit_logger' => \nsql\security\AuditLogger::class,
    'nsql\\security\\encryption' => \nsql\security\Encryption::class,
    'nsql\\security\\ip_resolver' => \nsql\security\IpResolver::class,
    'nsql\\security\\key_manager' => \nsql\security\KeyManager::class,
    'nsql\\security\\rate_limiter' => \nsql\security\RateLimiter::class,
    'nsql\\security\\security_manager' => \nsql\security\SecurityManager::class,
    'nsql\\security\\session_manager' => \nsql\security\SessionManager::class,
];
